defaults:
      - submitit_slurm

cpus_per_task: ${get_cpus_per_task:${mode}, ${num_actors}, ${test_after_train}}
gpus_per_node: 2
mem_gb: 64
nodes: 1
partition: learnfair
tasks_per_node: 1
timeout_min: 900
constraint: ${get_slurm_constraint:${.partition},${.gpus_per_node}}
comment: mvfst-rl
